### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Nevuly** [Nevuly/S510UA-BQ423-Hackintosh#1]
- [x] Fix Alcor SDCard Reader with config.plist
       (Currently, I modified AppleStorageDrivers.kext to enable SDCard reader.)
       Solution: Added AlcorSDCardReader.kext to load correct productID.
                       (Thanks to @whatnameisit)

- [x] Enable C-State for HWP
       (MSR Locked. Need to patch kernel to enable C-State without MSR Unlock.)
       Solution: Applied Pike R. Alpha's kernel to patch and disabled KernelPM in boot option.
       Test: Checked in hackintool.
          Result in hackintool:
                - I/O MWAIT Redirection Enable......... : 0 (not enabled)
                - CFG Lock............................. : 1 (MSR locked until next reset)
                - C3 State Auto Demotion............... : 1 (enabled)
                - C1 State Auto Demotion............... : 1 (enabled)
                - C3 State Undemotion.................. : 1 (enabled)
                - C1 State Undemotion.................. : 1 (enabled)
                - Package C-State Auto Demotion........ : 1 (enabled)
                - Package C-State Undemotion........... : 1 (enabled)

- [ ] Fix to work HDMI sound
       Temporary Solution: Rollbacked AppleALC to 1.4.2 and bring back CodecCommander and DSDT patches.
       Test: Applied in EFI partition, and rebooted.
       Warning: Don't update of AppleALC, or you will break HDMI audio again.

- [ ] Fix to work HEVC Codec (Netflix)

- [ ] Support OpenCore Bootloader
      OpenCore is not released stable yet, but Some users want to use it.

**Comment by whatnameisit** [comment]
매우 열정적이시네요.
1.4.3 이후로 AppleALC 자체가 문제가 있습니다. layout-id 3에 SSDT-CC와 CodecCommander를 사용해도 가끔씩 오디오가 인식이 안 됩니다. 그래서 이 부분은 Acidanthera에게 직접 문의하지 않는 이상 fix되기는 어려울 것 같고요. 지금 당장 macOS 10.16이 나오면 Lilu와 AppleALC 업데이트 되야 하는 점이 문제죠...
그리고 사용중인 SSDT-CC.aml은 CX8050이 아니라 CX20752에 해당합니다. CodecCommander.kext 안 Resources에 CX20752와 비교해보시면 알 수 있습니다: https://github.com/RehabMan/EAPD-Codec-Commander/blob/master/SSDT-CX20752.dsl
저는 제 깃에 CX8050이라고 적어놓은 것은 단지 tctien342가 본인 깃에 CX8050이라고 적어놓았고, 저는 사운드 설정 그대로 따라갔을 때 소리에 전혀 문제가 없어서 CX8050이라고 생각하고 있었는데 맞는지 아닌지 모르겠습니다... 그래서 AppleALC 1.4.3의 Vivobook CX8050의 layout-id 13을 사용했을 때 HDMI 소리가 안 나오는 것일수도...아니면 cowpod가 잘못 했는지..모르겠네요.
그리고 저는 SD 카드를 삽입했을 때 자동적으로 DeviceID가 6366으로 표기되는데...커맥은 전혀 감이 안 오네요 ㅋㅋㅋ 그리고 심심하시다면 KextsToPatch 지우고 Injector 켁스트 사용해보세요: 
[SDCardReaderAlcor.kext.zip](https://github.com/Nevuly/S510UA-BQ423-Hackintosh/files/4009985/SDCardReaderAlcor.kext.zip)
된다면 이걸 사용하시는게...왜냐하면 Y2I=는 데이터 크기가 너무 작아서 이 켁스트의 다른 부분도 패치될 가능성이 있어서요. 아니면 Y2I= 주위의 다른 데이터를 포함해서 패치하시거나, 오픈코어로 전환해서 패치할 위치와 횟수를 지정해주시면 됩니다만 갈수록 복잡해지네요...
이런건 뒤로 하고 우선 새해 복 많이 받으세요~

**Comment by Nevuly** [comment]
패치 제공해 주셔서 감사합니다 ㅠㅠ....
생각해보면 그럴지도 모르겠군요. 해당 디바이스 ID가 다른 모델에서도 같게 나올 가능성을 염두해 두면 whatnameisit님의 패치로 적용하는게 맞을 듯 싶습니다.
오늘도 또 하나 배워갑니다..ㅠㅠ..
일단 Acidanthera에게 직접 문의하는 것은 추후에 바로 할 예정입니다. (지금은 다른 작업도 많아버려서 바로 못하겠네요)
여튼 그렇습니다..ㅋㅋㅋ
whatnameisit님도 새해 복 많이 받으시고, 건강하세요!

**Comment by whatnameisit** [comment]
혹시 관심 있으시면 저는 OpenCore 0.5.4로 서로 다른 디스크 Catalina/Windows 듀얼부팅 가능하도록 세팅했는데, 참고해보세용. 같은 디스크는 아직 BlessOverride를 설정 안 해서 오류나는 중입니다...

**Comment by htogether** [comment]
혹시 사이드카 동작하나요?
https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh

사용중인 f510ua 가 위에것을 하면 와이파이가 작동하지 않아서

https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh

여기 참조해서 kext 넣으니 와이파이랑 블투가 잘 동작합니다. 마이크가 동작하지 않아서 CodecCommander 를 L/E 에 카피하니까 마이크도 잘 동작하는데 사이드카가 안되네요. 별다른 설정을 해야 하는지요?

에어2라서 안되는건지 내장 그래픽 설정이 잘못된건지. 다른 블투기기(마우스) 는 페어링에 문제가 없습니다.

**Comment by Nevuly** [comment]
@htogether 
사이드카는 아이패드 에어 3세대부터 지원합니다.

**Comment by Nevuly** [comment]
This project will be EOL to support.

I don't use Hackintosh anymore, So I just update kext and DSDT without test.

If you want to apply this in your device, Please test files and check bugs.

This project will be archive in April, 2020.

**Comment by Nevuly** [comment]
Now, this project is live again.

Updated to use OpenCore Bootloader, and support macOS Big Sur.
